on:
  push:
    branches:
      - master

jobs:
  local-prepare:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client/admin
    strategy:
      matrix:
        node-version: [ 18.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Build source and zip folder zip to file dist.zip
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: pwd
      - run: npm install --force
      - name: Build
        run: npm run build
        env:
          CI: false
      - run: zip -r build.zip build
      - name: scp file build.zip to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: './client/admin/build.zip'
          target: '~/online-shopping/cms'

      - name: Copy build.zip to /var/www/html/ folder
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/html/cms
            sudo cp ~/online-shopping/cms/build.zip .

      - name: unzip file build.zip
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/html/cms
            sudo unzip -o build.zip